name = "VibratoMonteCarlo"
uuid = "e6fc01e8-e6d3-4c93-80cb-ea8d1c9bc714"
authors = ["Nicola <nicola.scaramuzzino@yandex.com> and contributors"]
version = "0.1.0"

[deps]
FinancialMonteCarlo = "078f23cc-2637-5a1d-aba6-8a9ba9a6ff83"
Requires = "ae029012-a4dd-5104-9daa-d747884805df"

[compat]
FinancialMonteCarlo = "0.1, 0.2"
Requires = "1"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
