[deps]
DualNumbers = "fa6b7ba4-c1ee-5f82-b5fc-ecf0adba8f74"
FinancialMonteCarlo = "078f23cc-2637-5a1d-aba6-8a9ba9a6ff83"
FinancialToolbox = "2edd74a5-e968-5e45-af77-76d29aa6a478"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
HyperDualNumbers = "50ceba7f-c3ee-5a84-a6e8-3ad40456ec97"
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"

[compat]
BenchmarkTools = "0.7, 1"
DualNumbers = "0.5, 0.6"
FinancialMonteCarlo = "0.3"
FinancialToolbox = "0.5"
ForwardDiff = "0.10"
HyperDualNumbers = "2, 3, 4"
julia = "1"
